Repository eclipse-zenoh/zenoh-plugin-ros2dds, pull requests merged in 2024-09, with the labels that each got.

#250 fix: remove deprecated import with newer lock file
  Cargo.lock
  zenoh-plugin-ros2dds/src/discovered_entities.rs
  zenoh-plugin-ros2dds/src/routes_mgr.rs
Labels: release, internal

#243 Default config does not listen on `tcp/0.0.0.0:7447` by default
  DEFAULT_CONFIG.json5
Labels: documentation

#256 Update zenoh
  Cargo.lock
  zenoh-bridge-ros2dds/src/bridge_args.rs
  zenoh-plugin-ros2dds/src/lib.rs
  zenoh-plugin-ros2dds/src/route_action_cli.rs
  zenoh-plugin-ros2dds/src/route_action_srv.rs
  zenoh-plugin-ros2dds/src/route_publisher.rs
  zenoh-plugin-ros2dds/src/route_service_cli.rs
  zenoh-plugin-ros2dds/src/route_service_srv.rs
  zenoh-plugin-ros2dds/src/route_subscriber.rs
  zenoh-plugin-ros2dds/src/routes_mgr.rs
Labels: internal

#257 Update zenoh
  Cargo.lock
Labels: internal

#258 deps: align zenoh #1415
  Cargo.lock
  zenoh-bridge-ros2dds/src/main.rs
Labels: dependencies

#262 Align with Rust
  Cargo.lock
  Cargo.toml
  zenoh-bridge-ros2dds/Cargo.toml
  zenoh-bridge-ros2dds/src/main.rs
  zenoh-plugin-ros2dds/src/discovered_entities.rs
  zenoh-plugin-ros2dds/src/routes_mgr.rs
Labels: internal

#246 Update zenoh-bridge-ros2dds.service wrt. deprecated systemd settings
  zenoh-bridge-ros2dds/.service/zenoh-bridge-ros2dds.service
Labels: enhancement

#265 make upgrade command known to postrm
  zenoh-bridge-ros2dds/.deb/postrm
Labels: bug

#266 Align Rust with Reliability exported in zenoh::qos
  Cargo.lock
  zenoh-plugin-ros2dds/src/route_publisher.rs
Labels: internal

#275 chore: update release.yml for required labels
  .github/release.yml
Labels: internal

#277 Wrong order while composing the header and payload in ROS2 service.
  zenoh-plugin-ros2dds/src/route_service_cli.rs
  zenoh-plugin-ros2dds/src/route_service_srv.rs
Labels: bug
