Repository eclipse-zenoh/zenoh-plugin-ros2dds, pull requests merged in 2024-11, with the labels that each got.

#334 Support ROS_AUTOMATIC_DISCOVERY_RANGE and ROS_STATIC_PEERS
  Cargo.lock
  Cargo.toml
  DEFAULT_CONFIG.json5
  README.md
  zenoh-bridge-ros2dds/src/bridge_args.rs
  zenoh-plugin-ros2dds/Cargo.toml
  zenoh-plugin-ros2dds/src/config.rs
  zenoh-plugin-ros2dds/src/lib.rs
Labels: enhancement

#342 Document transient_local_cache_multiplier config
  DEFAULT_CONFIG.json5
Labels: documentation

#343 Fix invalid warning when $ROS_AUTOMATIC_DISCOVERY_RANGE is not defined
  zenoh-plugin-ros2dds/src/config.rs
  zenoh-plugin-ros2dds/src/lib.rs
Labels: bug

#344 On remote announcement, check local allow/deny config
  zenoh-plugin-ros2dds/src/lib.rs
Labels: bug

#346 Fix NodeInfo update after Reader discovery
  zenoh-plugin-ros2dds/src/discovered_entities.rs
Labels: bug
