Repository eclipse-zenoh/zenoh-plugin-ros2dds, pull requests merged in 2024-10, with the labels that each got.

#279 Use new Serialization and zenoh-ext API
  Cargo.lock
  Cargo.toml
  zenoh-plugin-ros2dds/src/discovered_entities.rs
  zenoh-plugin-ros2dds/src/lib.rs
  zenoh-plugin-ros2dds/src/ros2_utils.rs
  zenoh-plugin-ros2dds/src/route_service_cli.rs
  zenoh-plugin-ros2dds/src/route_service_srv.rs
  zenoh-plugin-ros2dds/src/route_subscriber.rs
  zenoh-plugin-ros2dds/src/routes_mgr.rs
Labels: enhancement, release, internal

#282 Fix sertype lookup failed warning
  zenoh-plugin-ros2dds/src/route_publisher.rs
  zenoh-plugin-ros2dds/src/route_service_cli.rs
  zenoh-plugin-ros2dds/src/route_service_srv.rs
  zenoh-plugin-ros2dds/src/route_subscriber.rs
Labels: bug

#288 chore: bump zenoh version
  zenoh-plugin-ros2dds/src/route_publisher.rs
  zenoh-plugin-ros2dds/src/route_service_srv.rs
  zenoh-plugin-ros2dds/src/route_subscriber.rs
Labels: internal

#296 Update DEFAULT_CONFIG.json5
  DEFAULT_CONFIG.json5
Labels: bug, documentation

#294 Update cyclors dependency to version with unique C symbols
  Cargo.lock
  Cargo.toml
Labels: bug

#301 Pin cyclors dependency to version 0.2.1
  Cargo.lock
  Cargo.toml
Labels: bug

#308 Updated cyclors to a version which mangles C symbols to allow different versions of the library to be loaded in the same static binary.
  Cargo.lock
  Cargo.toml
Labels: bug

#310 Support different config for ROS_LOCALHOST_ONLY.
  zenoh-plugin-ros2dds/src/lib.rs
Labels: bug

#312 Undeclare matching_listener explicitly to avoid deadlock.
  zenoh-plugin-ros2dds/src/route_publisher.rs
Labels: bug

#319 Use take instead of std::mem::replace.
  zenoh-plugin-ros2dds/src/route_publisher.rs
Labels: bug
