Repository eclipse-zenoh/zenoh-plugin-ros2dds, pull requests merged in 2024-12, with the labels that each got.

#351 Fix CI while running in ROS 2 Jazzy environment.
  zenoh-plugin-ros2dds/src/config.rs
Labels: internal

#349 Add type hash support (pub/sub only)
  zenoh-plugin-ros2dds/src/liveliness_mgt.rs
  zenoh-plugin-ros2dds/src/ros2_utils.rs
  zenoh-plugin-ros2dds/src/ros_discovery.rs
Labels: enhancement

#352 fix matching listener
  Cargo.lock
  zenoh-plugin-ros2dds/src/route_publisher.rs
Labels: internal

#350 Add ROS test with CI.
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  zenoh-plugin-ros2dds/Cargo.toml
  zenoh-plugin-ros2dds/src/ros_discovery.rs
  zenoh-plugin-ros2dds/tests/test.rs
Labels: internal

#355 Fix the description in shared memory option.
  zenoh-bridge-ros2dds/src/zenoh_args.rs
Labels: bug

#356 Route for Service Client: use the new Zenoh Querier and its matching_listener
  zenoh-plugin-ros2dds/src/route_service_cli.rs
  zenoh-plugin-ros2dds/src/route_service_srv.rs
Labels: enhancement

#358 Disable ros_test
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  zenoh-plugin-ros2dds/Cargo.toml
  zenoh-plugin-ros2dds/tests/test.rs
Labels: bug

#360 allow deprecated for fetching_subscriber usage
  Cargo.lock
  zenoh-plugin-ros2dds/src/lib.rs
Labels: internal

#361 clippy fixes
  zenoh-plugin-ros2dds/src/route_service_cli.rs
Labels: internal

#362 Move CI to an independent crate.
  .github/workflows/ci.yml
  Cargo.toml
  zenoh-plugin-ros2dds/Cargo.toml
  zenoh-plugin-ros2dds/tests/test.rs
  zenoh-test-ros2dds/Cargo.toml
  zenoh-test-ros2dds/tests/topic.rs
Labels: internal

#357 Support ROS 2 service in CI
  .github/workflows/ci.yml
  zenoh-test-ros2dds/Cargo.toml
  zenoh-test-ros2dds/tests/common.rs
  zenoh-test-ros2dds/tests/service.rs
  zenoh-test-ros2dds/tests/topic.rs
Labels: internal

#324 Support loading of both the ROS2 and DDS plugins on all supported platforms
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  README.md
  zenoh-bridge-ros2dds/Cargo.toml
  zenoh-plugin-ros2dds/Cargo.toml
Labels: bug

#364 fix: exclude internal from automatic changelog
  .github/release.yml
Labels: internal

#370 Add ROS 2 action CI for the bridge
  .github/workflows/ci.yml
  zenoh-test-ros2dds/tests/common.rs
  zenoh-test-ros2dds/tests/test_ros_client_zenoh_action.rs
  zenoh-test-ros2dds/tests/test_ros_client_zenoh_service.rs
  zenoh-test-ros2dds/tests/test_zenoh_client_ros_action.rs
  zenoh-test-ros2dds/tests/test_zenoh_client_ros_service.rs
  zenoh-test-ros2dds/tests/topic_pub_sub.rs
Labels: internal
