Repository eclipse-zenoh/zenoh-plugin-ros2dds, pull requests merged in 2024-08, with the labels that each got.

#217 Add an optional ":express" flag to "pub_priorities" configuration
  DEFAULT_CONFIG.json5
  zenoh-plugin-ros2dds/src/config.rs
  zenoh-plugin-ros2dds/src/route_publisher.rs
Labels: enhancement

#233 chore: update check-labels triggers
  .github/workflows/check-labels.yml
Labels: internal

#234 Fix -i / --id option: remap it to the ZenohID
  DEFAULT_CONFIG.json5
  README.md
  zenoh-bridge-ros2dds/src/bridge_args.rs
  zenoh-bridge-ros2dds/src/zenoh_args.rs
Labels: bug
