Repository eclipse-zenoh/zenoh-plugin-ros2dds, pull requests merged in 2025-03, with the labels that each got.

#415 compatibility with api changes due to namespace introduction
  Cargo.lock
  zenoh-plugin-ros2dds/src/lib.rs
  zenoh-plugin-ros2dds/src/route_publisher.rs
  zenoh-plugin-ros2dds/src/route_subscriber.rs
Labels: internal

#421 Bump cyclors to 0.2.6 - fix Windows build with recent MSVC
  Cargo.lock
  Cargo.toml
Labels: bug

#427 fix: update bump-deps-pattern to zenoh.*
  .github/workflows/release.yml
Labels: internal

#414 Bump Rust toolchain to 1.85
  rust-toolchain.toml
  zenoh-bridge-ros2dds/Cargo.toml
  zenoh-bridge-ros2dds/src/bridge_args.rs
  zenoh-plugin-ros2dds/src/dds_discovery.rs
  zenoh-plugin-ros2dds/src/node_info.rs
  zenoh-plugin-ros2dds/src/qos_helpers.rs
  zenoh-plugin-ros2dds/src/ros2_utils.rs
  zenoh-plugin-ros2dds/src/route_action_cli.rs
  zenoh-plugin-ros2dds/src/route_action_srv.rs
  zenoh-plugin-ros2dds/src/route_service_cli.rs
  zenoh-plugin-ros2dds/src/route_service_srv.rs
  zenoh-plugin-ros2dds/src/route_subscriber.rs
  zenoh-plugin-ros2dds/src/routes_mgr.rs
Labels: dependencies

#429 fix: add rust 1.75 CI check
  .github/workflows/ci.yml
Labels: internal
